import {FaExclamationCircle } from 'react-icons/fa';

export const notifications = [
  {
    id: '1',
    icon: FaExclamationCircle,
    title: 'Task Assigned',
    description: 'You have been assigned to a new task.You have been assigned to a new taskYou have been assigned to a new taskYou have been assigned to a new taskYou have been assigned to a new taskYou have been assigned to a new taskYou have been assigned to a new task',
    time: '2 minutes ago',
    isRead: false,
  },
  {
    id: '2',
    icon: FaExclamationCircle,
    title: 'Urgent: Deadline Approaching',
    description: 'The deadline for your project is approaching.',
    time: '1 hour ago',
    isRead: true,
  },
  {
    id: '3',
    icon: FaExclamationCircle,
    title: 'New Project Update',
    description: 'The project “UI redesign” has received a new update.',
    time: '3 hours ago',
    isRead: false,
  },
  {
    id: '4',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '5',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '6',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '7',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '8',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '9',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '10',
    icon: FaExclamationCircle,
    title: 'Warning: Task Overdue',
    description: 'The task "UI implementation" is overdue.',
    time: '1 day ago',
    isRead: true,
  },
  {
    id: '11',
    icon: FaExclamationCircle,
    title: 'Task Completed',
    description: 'The task “UI redesign” has been marked as complete.',
    time: '2 hours ago',
    isRead: false,
  },
  {
    id: '12',
    icon: FaExclamationCircle,
    title: 'Critical: Server Down',
    description: 'The server has gone down. Immediate action required.',
    time: '30 minutes ago',
    isRead: false,
  },
  {
    id: '13',
    icon: FaExclamationCircle,
    title: 'Task Completed',
    description: 'The task “API implementation” has been marked as complete.',
    time: '4 hours ago',
    isRead: true,
  },
  {
    id: '14',
    icon: FaExclamationCircle,
    title: 'Urgent: Security Update',
    description: 'A critical security update is available.',
    time: '5 hours ago',
    isRead: false,
  },
  {
    id: '15',
    icon: FaExclamationCircle,
    title: 'New Comment on Task',
    description: 'A new comment has been added to your task.',
    time: '6 hours ago',
    isRead: true,
  },
  {
    id: '16',
    icon: FaExclamationCircle,
    title: 'Warning: Disk Space Running Low',
    description: 'The disk space on the server is almost full.',
    time: '7 hours ago',
    isRead: false,
  },
  {
    id: '17',
    icon: FaExclamationCircle,
    title: 'Task Assigned',
    description: 'You have been assigned a new task for “Frontend Development”.',
    time: '8 hours ago',
    isRead: true,
  },
  {
    id: '18',
    icon: FaExclamationCircle,
    title: 'Critical: Database Issue',
    description: 'The database has encountered an issue.',
    time: '9 hours ago',
    isRead: false,
  },
  {
    id: '19',
    icon: FaExclamationCircle,
    title: 'Warning: Backup Failed',
    description: 'The scheduled backup has failed.',
    time: '10 hours ago',
    isRead: true,
  },
  {
    id: '20',
    icon: FaExclamationCircle,
    title: 'Task Completed',
    description: 'The task “Database Optimization” has been marked as complete.',
    time: '12 hours ago',
    isRead: false,
  },
];
